library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tibble)
library(stringr)
library(tidyverse)
library(xml2)
library(ggthemes)
library(readxl)
library(Rcpp)

library(ggalt)
library(cluster)
library(ranger)
library(iml)
options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
